CREATE DATABASE PROJETO;

/*CRIANDO TABELAS*/

CREATE TABLE CLIENTE ( NOME VARCHAR(30),
CPF INT(11),
EMAIL VARCHAR(30),
ENDERECO VARCHAR (100),
TELEFONE VARCHAR(30),
SEXO CHAR(1));

/*CONECTANDO*/

USE PROJETO;

/*MOSTRANDO TABELAS OU BANCOS DE DADOS*/

SHOW TABLES;
SHOW DATABASES;

/*DESCOBRINDO QUAL DATABASE VOCE ESTÁ CONECTADO*/

STATUS;

/*DESCREVENDO UMA TABELA ESPECÍFICA E MOSTRAR SEUS ATRIBUTOS E TIPOS*/

DESC CLIENTE;

/*INSERINDO REGISTROS NA TABELA*/

INSERT INTO CLIENTE (NOME, ENDERECO, TELEFONE, CPF, SEXO, EMAIL) VALUES ('GAMBIARRA', 'RUA PETUNIA - 
JARDIM DAS FLORES - OASCO - SP', 124587, '124587532', 'M', 'ALOALO@OLAOLA.COM');

/*PROJETANDO CAMPOS DE UMA TABELA*/

SELECT NOME, ENDERECO FROM CLIENTE;

SELECT NOME, SEXO, TELEFONE FROM CLIENTE;

/*PROJETANDO COM ALIAS*/

SELECT NOME AS CLIENTES, TELEFONE AS CELULAR, ENDERECO FROM CLIENTE;

SELECT NOW() AS DATA_HORA;
)

/*USE * SOMENTE PARA FINS ACADEMICOS POIS PODE RESULTAR EM PROBLEMAS*/

SELECT * FROM CLIENTE; /* NUNCA USE EM UMA EMPRESA */

/*UTILIZANDO SELEÇÃO COM WHERE*/

SELECT NOME FROM CLIENTE WHERE SEXO = 'F';

SELECT NOME, ENDERECO, SEXO FROM CLIENTE WHERE SEXO = 'M';

/*UTILIZANDO SELEÇÕES COM LIKE - ESSE COMANDO NECESSITA DO CARACTER CORINGA PARA FUNCIONAR 
DE UMA MANEIRA MELHOR - CARACTER CORINGA = %(LÊ-SE COMO 'QUALQUER COISA')*/

SELECT NOME, ENDERECO, SEXO FROM CLIENTE WHERE ENDERECO LIKE '%GRECIA%';

SELECT NOME FROM CLIENTE WHERE TELEFONE LIKE '%1%';

SELECT NOME, SEXO, TELEFONE, CPF, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%JARDIM%';

/*ALTERANDO DADOS*/

UPDATE CLIENTE SET NOME = "gUSTAVO mONTENEGRO" WHERE NOME = "GUSTAVO";
