CREATE DATABASE LIVRARIA;

SHOW DATABASES;

USE LIVRARIA;

SHOW TABLES;

DESC LIVROS;

CREATE TABLE LIVROS( 
NOME DO LIVRO VARCHAR(30),
NOME DO AUTOR VARCHAR(50), 
SEXO DO AUTOR VARCHAR(20), 
NUMERO DE PAGINAS INT(4),    /*NUNCA USE ESPAÇO ENTRE AS PLAVRAS*/
NOME DA EDITORA VARCHAR(30), 
VALOR DO LIVRO DOUBLE(6,2), 
ESTADO DA EDITORA CHAR(2), 
ANO DE PUBLICACAO INT(4)
);

CREATE TABLE LIVROS(
NOME_DO_LIVRO VARCHAR(30),
NOME_DO_AUTOR VARCHAR(50),
SEXO_DO_AUTOR VARCHAR(20),
NUMERO_DE_PAGINAS INT(4),
NOME_DA_EDITORA VARCHAR(30),
VALOR_DO_LIVRO DOUBLE(6,2),
ESTADO_DA_EDITORA CHAR(2),
ANO_DE_PUBLICACAO INT(4)
);

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'CAVALEIRO REAL', 'ANA CLAUDIA',
'FEMININO', 465, 'ATLAS', 49.9, 'RJ', 2009 );

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'SQL PARA LEIGOS', 'JOAO NUNES', 
'MASCULINO', 450, 'ADDISON', 98, 'SP', 2018 );

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'RECEITAS CASEIRAS', 'CELIA TAVARES', 
'FEMININO', 210, 'ATLAS', 45, 'RJ', 2008 );

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'PESSOAS EFETIVAS', 'EDUARDO SANTOS', 
'MASCULINO', 390, 'BETA', 78.99, 'RJ', 2018);

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'HABITOS SAUDAVEIS', 'EDUARDO SANTOS', 
'MASCULINO', 630, 'BETA', 150.98, 'RJ', 2019);

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'A CASA MARROM', 
'HERMES MACEDO', 'MASCULINO', 250, 'BUBA', 60, 'MG', 2016  );

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'ESTACIO', 
'GERALDO FRANCISCO', 'MASCULINO', 310, 'INSIGNIA', 100, 'ES', 2015 );

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'PARA SEMPRE AMIGAS', 'LEDA SILVA',
'FEMININO', 510, 'INSIGNIA', 78.98, 'ES', 2011 );

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'COPAS INESQUECIVEIS',
'MARCO ALCANTARA', 'MASCULINO', 200, 'LARSON', 130.98, 'RS', 2018 );

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS,
NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES( 'O PODER DA MENTE',
'CLARA MAFRA', 'FEMININO', 120, 'CONTINENTAL', 56.58, 'SP', 2017 );


/*EXERCICIOS*/

/*2 - */ 

SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;

/*3 -*/

SELECT NOME_DO_LIVRO, ESTADO_DA_EDITORA FROM LIVROS WHERE SEXO_DO_AUTOR = 'MASCULINO';


/*4 - */

SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS WHERE SEXO_DO_AUTOR = 'FEMININO';

/*5 - */

SELECT VALOR_DO_LIVRO FROM LIVROS WHERE ESTADO_DA_EDITORA = 'SP';

/*DESAFIO*/

SELECT NOME_DO_LIVRO, NOME_DO_AUTOR, NUMERO_DE_PAGINAS, VALOR_DO_LIVRO, ESTADO_DA_EDITORA FROM LIVROS WHERE SEXO_DO_AUTOR = "MASCULINO" AND (ESTADO_DA_EDITORA = 'SP' OR ESTADO_DA_EDITORA = 'RJ');


/*ORDENAÇÃO DE DADOS*/


SELECT * FROM LIVROS ORDER BY NOME_DO_LIVRO ASC; /*ASCENDENTE*/

SELECT NOME_DA_EDITORA, NOME_DO_AUTOR, NOME_DO_LIVRO FROM LIVROS ORDER BY NOME_DO_AUTOR DESC; /*DESCENDENTE*/


/*OPERADORES LÓGICOS*/

/*
OR -> BASTA APENAS UMA DAS CONDIÇÕES SER VERDADEIRA PARA OBTER UM RESULTADO VERDADEIRO

AND -> APENAS QUANDO AMBAS AS CONDIÇÕES SÃO VERDADEIRAS QUE É POSSIVEL OBTER UM RESULTADO VERDADEIRO
*/


SELECT NOME_DO_LIVRO, NOME_DO_AUTOR, ESTADO_DA_EDITORA, SEXO_DO_AUTOR, NOME_DA_EDITORA FROM LIVROS WHERE ESTADO_DA_EDITORA = "SP" AND (SEXO_DO_AUTOR = "MASCULINO" AND NOME_DA_EDITORA = "BETA" );


/*ALTERANDO DADOS*/

UPDATE LIVROS SET SEXO_DO_AUTOR = "MASCULINO", NUMERO_DE_PAGINAS = "390" WHERE NOME_DO_AUTOR = "ERIC JAGER";




